/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example.tarefas.IA941A;

import ws3dproxy.WS3DProxy;
import ws3dproxy.model.Creature;
import ws3dproxy.model.World;

public class App {

    public Creature c;
    public World w;
    public int width;
    public int height;
    public WS3DProxy proxy;

    public String getGreeting() {
        return ("Greetings...");
    }

    public App() {
        proxy = new WS3DProxy();
        try {
            w = World.getInstance();
            width = w.getEnvironmentWidth();
            height = w.getEnvironmentHeight();

            w.reset();
        } catch (Exception e) {
            System.out.println("Erro capturado");
        }
    }

    public static void main(String[] args) {
        App app = new App();
        MainFrame frame = new MainFrame(app);
        frame.setVisible(true);
    }
}
