/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.example.tarefas.IA941A;

import java.awt.event.KeyEvent;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.util.Random;
import ws3dproxy.WS3DProxy;
import ws3dproxy.model.Creature;
import ws3dproxy.model.Leaflet;

/**
 *
 * @author daniel
 */
public class MainFrame extends javax.swing.JFrame {

    private App app;
    private Map<String, Creature> CreaturesMap = new HashMap<String, Creature>();
    private Creature selectedCreature = null;
    private boolean leftKeyPressed = false;
    private boolean upKeyPressed = false;
    private boolean rightKeyPressed = false;
    private boolean downKeyPressed = false;

    /**
     * Creates new form MainFrame
     */
    public MainFrame(App app) {
        initComponents();
        this.app = app;
        DimesionsLabel.setText("World dimensions - width: " + app.width + "; height: " + app.height);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        CreateCreatureButton = new javax.swing.JButton();
        XCreatureTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        YCreatureTextField = new javax.swing.JTextField();
        CreatureColorComboBox = new javax.swing.JComboBox<>();
        DimesionsLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        CreateFoodButton = new javax.swing.JButton();
        XFoodTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        YFoodTextField = new javax.swing.JTextField();
        FoodTypeComboBox = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        CreateJewelButton = new javax.swing.JButton();
        XJewelTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        YJewelTextField = new javax.swing.JTextField();
        JewelTypeComboBox = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        CreateBrickButton = new javax.swing.JButton();
        X1BrickTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Y1BrickTextField = new javax.swing.JTextField();
        BrickTypeComboBox = new javax.swing.JComboBox<>();
        X2BrickTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Y2BrickTextField = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        MoveCreatureButton = new javax.swing.JButton();
        CreaturesComboBox = new javax.swing.JComboBox<>();
        XMoveTextField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        YMoveTextField = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        GetThingsTextArea = new javax.swing.JTextArea();
        getLeafletsButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Leaflet1TextArea = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        Leaflet2TextArea = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        Leaflet3TextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        CreateCreatureButton.setText("Create Creature");
        CreateCreatureButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateCreatureButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("X:");

        jLabel2.setText("Y:");

        CreatureColorComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "yellow", "red" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CreateCreatureButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(XCreatureTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(YCreatureTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CreatureColorComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CreateCreatureButton)
                    .addComponent(jLabel1)
                    .addComponent(XCreatureTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(YCreatureTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CreatureColorComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        CreateFoodButton.setText("Create Food");
        CreateFoodButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateFoodButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("X:");

        jLabel4.setText("Y:");

        FoodTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "apple", "nut" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CreateFoodButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(XFoodTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(YFoodTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FoodTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CreateFoodButton)
                    .addComponent(jLabel3)
                    .addComponent(XFoodTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(YFoodTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FoodTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        CreateJewelButton.setText("Create Jewel");
        CreateJewelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateJewelButtonActionPerformed(evt);
            }
        });

        jLabel5.setText("X:");

        jLabel6.setText("Y:");

        JewelTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Red", "Green", "Blue", "Yellow", "Magenta", "White" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CreateJewelButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(XJewelTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(YJewelTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JewelTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CreateJewelButton)
                    .addComponent(jLabel5)
                    .addComponent(XJewelTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(YJewelTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JewelTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        CreateBrickButton.setText("Create Brick");
        CreateBrickButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateBrickButtonActionPerformed(evt);
            }
        });

        jLabel7.setText("X1:");
        jLabel7.setToolTipText("");

        jLabel8.setText("Y1:");

        BrickTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Red", "Green", "Blue", "Yellow", "Magenta", "White" }));

        jLabel9.setText("X2:");
        jLabel9.setToolTipText("");

        jLabel10.setText("Y2:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CreateBrickButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(X1BrickTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Y1BrickTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(X2BrickTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Y2BrickTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BrickTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(X2BrickTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10)
                        .addComponent(Y2BrickTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BrickTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(CreateBrickButton)
                        .addComponent(jLabel7)
                        .addComponent(X1BrickTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)
                        .addComponent(Y1BrickTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        MoveCreatureButton.setText("Click to move");
        MoveCreatureButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                MoveCreatureButtonKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                MoveCreatureButtonKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                MoveCreatureButtonKeyTyped(evt);
            }
        });

        CreaturesComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreaturesComboBoxActionPerformed(evt);
            }
        });

        jLabel11.setText("X:");

        jLabel12.setText("Y:");

        jButton6.setText("Move to:");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton1.setText("Get things in vision");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        GetThingsTextArea.setColumns(20);
        GetThingsTextArea.setRows(5);
        jScrollPane1.setViewportView(GetThingsTextArea);

        getLeafletsButton.setText("getLeaflets");
        getLeafletsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getLeafletsButtonActionPerformed(evt);
            }
        });

        Leaflet1TextArea.setColumns(20);
        Leaflet1TextArea.setRows(5);
        jScrollPane2.setViewportView(Leaflet1TextArea);

        Leaflet2TextArea.setColumns(20);
        Leaflet2TextArea.setRows(5);
        jScrollPane3.setViewportView(Leaflet2TextArea);

        Leaflet3TextArea.setColumns(20);
        Leaflet3TextArea.setRows(5);
        jScrollPane4.setViewportView(Leaflet3TextArea);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 509, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(CreaturesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(MoveCreatureButton))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jButton6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(XMoveTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(YMoveTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton1)
                            .addComponent(getLeafletsButton)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CreaturesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MoveCreatureButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(jLabel11)
                    .addComponent(XMoveTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(YMoveTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(getLeafletsButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(152, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DimesionsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 9, Short.MAX_VALUE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DimesionsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CreateCreatureButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateCreatureButtonActionPerformed
        String sX = XCreatureTextField.getText();
        String sY = YCreatureTextField.getText();
        int x;
        int y;
        try {
            x = Integer.parseInt(sX);
            y = Integer.parseInt(sY);
            if (x > app.width || y > app.height) {
                throw new Exception();
            }
        } catch (Exception e) {
            Random rand = new Random();
            x = rand.nextInt(app.width);
            y = rand.nextInt(app.height);
        }

        int color = CreatureColorComboBox.getSelectedIndex();

        try {
            Creature c = app.proxy.createCreature(x, y, 0, color);
            CreaturesComboBox.addItem(c.getName());
            CreaturesMap.put(c.getName(), c);
            if (selectedCreature == null) {
                selectedCreature = c;
            }
            c.start();
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_CreateCreatureButtonActionPerformed

    private void CreateFoodButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateFoodButtonActionPerformed
        String sX = XFoodTextField.getText();
        String sY = YFoodTextField.getText();
        int x;
        int y;
        try {
            x = Integer.parseInt(sX);
            y = Integer.parseInt(sY);
            if (x > app.width || y > app.height) {
                throw new Exception();
            }
        } catch (Exception e) {
            Random rand = new Random();
            x = rand.nextInt(app.width);
            y = rand.nextInt(app.height);
        }

        int type = FoodTypeComboBox.getSelectedIndex();

        try {
            app.w.createFood(type, x, y);
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_CreateFoodButtonActionPerformed

    private void CreateJewelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateJewelButtonActionPerformed
        String sX = XJewelTextField.getText();
        String sY = YJewelTextField.getText();
        int x;
        int y;
        try {
            x = Integer.parseInt(sX);
            y = Integer.parseInt(sY);
            if (x > app.width || y > app.height) {
                throw new Exception();
            }
        } catch (Exception e) {
            Random rand = new Random();
            x = rand.nextInt(app.width);
            y = rand.nextInt(app.height);
        }

        int type = JewelTypeComboBox.getSelectedIndex();

        try {
            app.w.createJewel(type, x, y);
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_CreateJewelButtonActionPerformed

    private void CreateBrickButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateBrickButtonActionPerformed
        String sX1 = X1BrickTextField.getText();
        String sY1 = Y1BrickTextField.getText();
        String sX2 = X2BrickTextField.getText();
        String sY2 = Y2BrickTextField.getText();
        int x1 = -1;
        int y1 = -1;
        int x2 = -1;
        int y2 = -1;
        try {
            x1 = Integer.parseInt(sX1);
            y1 = Integer.parseInt(sY1);
            x2 = Integer.parseInt(sX2);
            y2 = Integer.parseInt(sY2);
            if (x1 > app.width || y1 > app.height || x2 > app.width || y2 > app.height) {
                x1 = -1;
                y1 = -1;
                x2 = -1;
                y2 = -1;
                throw new Exception();
            }
        } catch (Exception e) {
            System.out.println("Brick dimensions out of bounds");
        }

        if (x1 < 0 || y1 < 0 || x2 < 0 || y2 < 0) {
            return;
        }

        int type = BrickTypeComboBox.getSelectedIndex();

        try {
            app.w.createBrick(type, x1, y1, x2, y2);
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_CreateBrickButtonActionPerformed

    private void MoveCreatureButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MoveCreatureButtonKeyPressed
        int keyCode = evt.getKeyCode();
        switch (keyCode) {
            case KeyEvent.VK_UP:
                if (!upKeyPressed) {
                    try {
                        selectedCreature.move(20, 20, 0);
                    } catch (Exception e) {
                        System.out.println(e);
                    }
                    upKeyPressed = true;
                }
                break;
            case KeyEvent.VK_DOWN:
                if (!downKeyPressed) {
                    try {
                        selectedCreature.move(-20, -20, 0);
                    } catch (Exception e) {
                        System.out.println(e);
                    }
                    downKeyPressed = true;
                }
                break;
            case KeyEvent.VK_LEFT:
                if (!leftKeyPressed) {
                    try {
                        selectedCreature.move(20, -20, 0);
                    } catch (Exception e) {
                        System.out.println(e);
                    }
                    leftKeyPressed = true;
                }
                break;
            case KeyEvent.VK_RIGHT:
                if (!rightKeyPressed) {
                    try {
                        selectedCreature.move(-20, 20, 0);
                    } catch (Exception e) {
                        System.out.println(e);
                    }
                    rightKeyPressed = true;
                }
                break;
        }
    }//GEN-LAST:event_MoveCreatureButtonKeyPressed

    private void CreaturesComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreaturesComboBoxActionPerformed
        String creatureName = (String) CreaturesComboBox.getSelectedItem();
        Creature c = CreaturesMap.get(creatureName);
        selectedCreature = c;
        try {
            c.start();
        } catch (Exception e) {
            System.out.println();
        }
    }//GEN-LAST:event_CreaturesComboBoxActionPerformed

    private void MoveCreatureButtonKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MoveCreatureButtonKeyTyped

    }//GEN-LAST:event_MoveCreatureButtonKeyTyped

    private void MoveCreatureButtonKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MoveCreatureButtonKeyReleased
        int keyCode = evt.getKeyCode();
        switch (keyCode) {
            case KeyEvent.VK_UP:
                try {
                    selectedCreature.stop();

                } catch (Exception e) {
                    System.out.println(e);
                }
                upKeyPressed = false;
                break;
            case KeyEvent.VK_DOWN:
                try {
                    selectedCreature.stop();

                } catch (Exception e) {
                    System.out.println(e);
                }
                downKeyPressed = false;
                break;
            case KeyEvent.VK_LEFT:
                try {
                    selectedCreature.stop();

                } catch (Exception e) {
                    System.out.println(e);
                }
                leftKeyPressed = false;
                break;
            case KeyEvent.VK_RIGHT:
                try {
                    selectedCreature.stop();

                } catch (Exception e) {
                    System.out.println(e);
                }
                rightKeyPressed = false;
                break;
        }
    }//GEN-LAST:event_MoveCreatureButtonKeyReleased

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        String sX = XMoveTextField.getText();
        String sY = YMoveTextField.getText();
        int x = 0;
        int y = 0;
        try {
            x = Integer.parseInt(sX);
            y = Integer.parseInt(sY);
            if (x > app.width || y > app.height) {
                throw new Exception();
            }
        } catch (Exception e) {
            System.out.println(e);
        }

        try {
            selectedCreature.moveto(30, x, y);
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        selectedCreature.updateState();
        GetThingsTextArea.setText(selectedCreature.getThingsInVision().toString());
    }//GEN-LAST:event_jButton1ActionPerformed

    private String leafletString(Leaflet l) {
        String ret = "LeafletID: " + l.getID() + "\n";
        for (Iterator<String> iter = l.getItems().keySet().iterator(); iter.hasNext();) {
            String str = iter.next(); //jewel color
            ret = ret + str + " ";
            //(total number) (collected)
            ret = ret + l.getItems().get(str)[0] + " ";
            ret = ret + l.getItems().get(str)[1] + "\n";
        }
        ret = ret + " payment= " + l.getPayment() + "\n" + " situation= " + l.getSituation() + " ";
        return ret;
    }
    
    private void getLeafletsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getLeafletsButtonActionPerformed
        List<Leaflet> leaflets = selectedCreature.getLeaflets();
        Leaflet1TextArea.setText(leafletString(leaflets.get(0)));
        Leaflet2TextArea.setText(leafletString(leaflets.get(1)));
        Leaflet3TextArea.setText(leafletString(leaflets.get(2)));
    }//GEN-LAST:event_getLeafletsButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> BrickTypeComboBox;
    private javax.swing.JButton CreateBrickButton;
    private javax.swing.JButton CreateCreatureButton;
    private javax.swing.JButton CreateFoodButton;
    private javax.swing.JButton CreateJewelButton;
    private javax.swing.JComboBox<String> CreatureColorComboBox;
    private javax.swing.JComboBox<String> CreaturesComboBox;
    private javax.swing.JLabel DimesionsLabel;
    private javax.swing.JComboBox<String> FoodTypeComboBox;
    private javax.swing.JTextArea GetThingsTextArea;
    private javax.swing.JComboBox<String> JewelTypeComboBox;
    private javax.swing.JTextArea Leaflet1TextArea;
    private javax.swing.JTextArea Leaflet2TextArea;
    private javax.swing.JTextArea Leaflet3TextArea;
    private javax.swing.JButton MoveCreatureButton;
    private javax.swing.JTextField X1BrickTextField;
    private javax.swing.JTextField X2BrickTextField;
    private javax.swing.JTextField XCreatureTextField;
    private javax.swing.JTextField XFoodTextField;
    private javax.swing.JTextField XJewelTextField;
    private javax.swing.JTextField XMoveTextField;
    private javax.swing.JTextField Y1BrickTextField;
    private javax.swing.JTextField Y2BrickTextField;
    private javax.swing.JTextField YCreatureTextField;
    private javax.swing.JTextField YFoodTextField;
    private javax.swing.JTextField YJewelTextField;
    private javax.swing.JTextField YMoveTextField;
    private javax.swing.JButton getLeafletsButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    // End of variables declaration//GEN-END:variables
}
